spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 120s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: comment_service_comments
          uri: lb://comment-service
          predicates:
            - Path=/events/*/comments, /admin/comments/**, /users/*/comments/**
          filters:
            - CircuitBreaker=mainCircuit

        - id: event_service_categories
          uri: lb://event-service
          predicates:
            - Path=/categories/**, /admin/categories/**
          filters:
            - CircuitBreaker=mainCircuit

        - id: event_service_compilations
          uri: lb://event-service
          predicates:
            - Path=/compilations/**, /admin/compilations/**
          filters:
            - CircuitBreaker=mainCircuit

        - id: event_service_events
          uri: lb://event-service
          predicates:
            - Path=/events/**, /users/*/events/**, /admin/events/**
          filters:
            - CircuitBreaker=mainCircuit

        - id: request_service_requests
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
          filters:
            - CircuitBreaker=mainCircuit

        - id: user_service_users
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - CircuitBreaker=mainCircuit

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 5
        minimumNumberOfCalls: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 5s
  timelimiter:
    configs:
      default:
        timeoutDuration: 60s
        cancelRunningFuture: false


server:
  port:
    8080